name: js_utils
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Vadim Tsushko <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <1.0.0'
  path: '>=1.3.9 <2.0.0'
  browser: '>=0.10.0 <1.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
